@include('layout/css')
    @include('layout/header')
    @include('layout/imgcompte')
    @include('layout/connexionCompte')
    @include('flashy::message')
    @include('layout/go-up')
    @include('layout/footer')
